"""`amnesic-pi-anon` -- the anonymity stages.

`randomize-mac` and `verify-zero-ip` are pre-network: they run before the
firewall, and therefore long before Tor exists. Nothing in those two paths may
touch Tor, the network, or persistent state.

`verify-tor-path` is the opposite end of the boot: it runs after Tor and is the
last gate before the appliance declares itself ready.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence

from .authority import Authority, Check
from .clihelp import add_common, authority_for, load_config, report, require_root
from .mac import MacError, randomize_interface
from .netif import InterfaceError, NetworkInterfaces
from .torpath import verify_tor_path


def cmd_randomize_mac(args: argparse.Namespace) -> int:
    """Randomize every configured interface's MAC, with verified readback.

    Exits nonzero if any interface never appears, if the driver rejects the
    change, or if the readback does not match what this process generated. A
    NIC that silently ignores address changes must fail loudly here rather than
    let the appliance claim an anonymity property it does not have.
    """
    denied = require_root("amnesic-pi-anon randomize-mac")
    if denied is not None:
        return denied

    config = load_config(args.config)
    interfaces = NetworkInterfaces.default()
    failures: list[str] = []
    for iface in config.resolved_mac_ifaces():
        try:
            result = randomize_interface(
                iface, interfaces, wait_seconds=config.iface_wait_seconds
            )
        except MacError as exc:
            failures.append(str(exc))
            print(f"FAIL  {iface}  {exc}", file=sys.stderr)
            continue
        permanent = result.permanent or "unavailable from this driver"
        print(f"PASS  {iface}  assigned {result.assigned} (burned-in: {permanent})")

    if failures:
        print(
            f"MAC randomization failed on {len(failures)} interface(s); "
            "refusing to continue to the firewall stage",
            file=sys.stderr,
        )
        return 1
    return 0


def cmd_verify_zero_ip(args: argparse.Namespace) -> int:
    """Assert the role interfaces carry no IP address before the network starts.

    An address surviving into this stage means something configured the
    interface ahead of the authority gate.
    """
    config = load_config(args.config)
    interfaces = NetworkInterfaces.default()
    checks: list[Check] = []
    for iface in (config.uplink_if, config.client_if):
        try:
            interfaces.wait_for(iface, timeout=config.iface_wait_seconds)
            addresses = interfaces.assigned_addresses(iface)
        except InterfaceError as exc:
            checks.append(Check(f"{iface} zero-IP", False, str(exc)))
            continue
        # IPv6 link-local is generated by the kernel from the (now randomized)
        # MAC or a stable secret and is not a configured address, so it does not
        # violate the zero-IP posture.
        routable = [entry for entry in addresses if not entry.startswith("inet6 fe80:")]
        checks.append(
            Check(
                f"{iface} zero-IP",
                not routable,
                "no address configured" if not routable else ", ".join(routable),
            )
        )
    return 0 if report(checks) else 1


def cmd_verify_tor_path(args: argparse.Namespace) -> int:
    config = load_config(args.config)
    authority: Authority = authority_for(args)
    checks = verify_tor_path(
        config, authority, require_observation=getattr(args, "require_observation", False)
    )
    return 0 if report(checks) else 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="amnesic-pi-anon",
        description="Amnesic Pi anonymity stages (pre-network hardening and post-Tor posture).",
    )
    add_common(parser)
    sub = parser.add_subparsers(dest="command", required=True)

    mac = sub.add_parser(
        "randomize-mac", help="randomize interface MACs and verify the change took effect"
    )
    mac.set_defaults(func=cmd_randomize_mac)

    zero_ip = sub.add_parser(
        "verify-zero-ip", help="assert the role interfaces carry no IP before the network starts"
    )
    zero_ip.set_defaults(func=cmd_verify_zero_ip)

    tor_path = sub.add_parser(
        "verify-tor-path",
        help="post-Tor egress posture verification; runs after Tor, never before the firewall",
    )
    tor_path.add_argument(
        "--require-observation",
        action="store_true",
        help="treat third-party echo telemetry as a hard gate (hardware release testing only)",
    )
    tor_path.set_defaults(func=cmd_verify_tor_path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
